### ISSUE TITLE
Uploading V16 mock-ups 

### ISSUE THREAD

**Issue by elinaru** [caciviclab/caciviclab.github.io#14]
sm-desktop-1-home
![sm-desktop-1-home](https://cloud.githubusercontent.com/assets/6467815/18463160/054bd55e-793d-11e6-8cff-a152645b3f62.png)

sm-desktop-2-search-and-validation-errors
![sm-desktop-2-search-and-validation-errors](https://cloud.githubusercontent.com/assets/6467815/18463161/0553a752-793d-11e6-9fd0-8983541d5c2e.png)

sm-desktop-3-local_list-standard-reducedscope
![sm-desktop-3-local_list-standard-reducedscope](https://cloud.githubusercontent.com/assets/6467815/18463165/05610ef6-793d-11e6-9144-cf37361a6f30.png)

sm-desktop-candidate-4-local_list-all-candidates
![sm-desktop-candidate-4-local_list-all-candidates](https://cloud.githubusercontent.com/assets/6467815/18463163/055f4d32-793d-11e6-8bcd-806625fbd337.png)

sm-desktop-measure-4-local_list-all-iecs-and-abstract
![sm-desktop-measure-4-local_list-all-iecs-and-abstract](https://cloud.githubusercontent.com/assets/6467815/18463164/055f8798-793d-11e6-85ca-7db484974798.png)

sm-desktop-measure-5-iec-details-page
![sm-desktop-measure-5-iec-details-page](https://cloud.githubusercontent.com/assets/6467815/18463162/05599be4-793d-11e6-8c73-5f360ae21f4b.png)

sm-mobile-1-home
![sm-mobile-1-home](https://cloud.githubusercontent.com/assets/6467815/18463166/05790d9e-793d-11e6-859d-54243327fba8.png)

sm-mobile-2-search-and-validation-errors
![sm-mobile-2-search-and-validation-errors](https://cloud.githubusercontent.com/assets/6467815/18463168/059b04bc-793d-11e6-8ff4-ba7ca71d4470.png)

sm-mobile-3-local-election-list
![sm-mobile-3-local-election-list](https://cloud.githubusercontent.com/assets/6467815/18463169/059beee0-793d-11e6-844a-efca2de9a825.png)

sm-mobile-4-list-of-candidates
![sm-mobile-4-list-of-candidates](https://cloud.githubusercontent.com/assets/6467815/18463170/059c1cb2-793d-11e6-8625-fb89eb227922.png)

sm-mobile-4-measure-detailpage
![sm-mobile-4-measure-detailpage](https://cloud.githubusercontent.com/assets/6467815/18463167/0599ea64-793d-11e6-98d7-8c0e79e93ea7.png)

sm-mobile-5-candidate-detailpage
![sm-mobile-5-candidate-detailpage](https://cloud.githubusercontent.com/assets/6467815/18463171/059d2788-793d-11e6-8b60-9046077f27de.png)

sm-mobile-5-measure-supporters
![sm-mobile-5-measure-supporters](https://cloud.githubusercontent.com/assets/6467815/18463175/05f1c07c-793d-11e6-9287-0a63dca0d63d.png)

sm-mobile-6-candidate-contributions
![sm-mobile-6-candidate-contributions](https://cloud.githubusercontent.com/assets/6467815/18463172/05c7e144-793d-11e6-9224-8c9dcfafd27c.png)

sm-mobile-6-committee-detailpage
![sm-mobile-6-committee-detailpage](https://cloud.githubusercontent.com/assets/6467815/18463174/05d21f88-793d-11e6-8bfe-2885d4f055ad.png)

sm-mobile-7-committee-contributors
![sm-mobile-7-committee-contributors](https://cloud.githubusercontent.com/assets/6467815/18463173/05d13208-793d-11e6-9a7b-dd71c42be190.png)

desktop-1-home
![desktop-1-home](https://cloud.githubusercontent.com/assets/6467815/18463178/0c3f57c8-793d-11e6-9b1d-799d10864775.png)

desktop-2-search-and-validation-errors
![desktop-2-search-and-validation-errors](https://cloud.githubusercontent.com/assets/6467815/18463188/0cc21c26-793d-11e6-96f5-b3c99e3b9a77.png)

desktop-3-local_list-standard-reducedscope
![desktop-3-local_list-standard-reducedscope](https://cloud.githubusercontent.com/assets/6467815/18463180/0c5df728-793d-11e6-9ddc-0118d0e91bc8.png)

desktop-candidate-4-local_list-all-candidates
![desktop-candidate-4-local_list-all-candidates](https://cloud.githubusercontent.com/assets/6467815/18463181/0c5f0e7e-793d-11e6-82c1-0998e1b89e3f.png)

desktop-measure-4-local_list-all-iecs-and-abstract
![desktop-measure-4-local_list-all-iecs-and-abstract](https://cloud.githubusercontent.com/assets/6467815/18463182/0c5f9006-793d-11e6-9a65-234ff43e43da.png)

desktop-measure-5-iec details page
![desktop-measure-5-iec details page](https://cloud.githubusercontent.com/assets/6467815/18463179/0c5ddf18-793d-11e6-9ae2-81e45c1a7e9e.png)

mobile-1-home
![mobile-1-home](https://cloud.githubusercontent.com/assets/6467815/18463183/0c853dba-793d-11e6-9ff8-57461c2cf9b6.png)

mobile-2-search-and-validation-errors
![mobile-2-search-and-validation-errors](https://cloud.githubusercontent.com/assets/6467815/18463184/0c897a2e-793d-11e6-8283-2484015f04f1.png)

mobile-3-local-election-list
![mobile-3-local-election-list](https://cloud.githubusercontent.com/assets/6467815/18463185/0c8a1588-793d-11e6-8a8a-85b9cff8f44f.png)

mobile-4-list-of-candidates
![mobile-4-list-of-candidates](https://cloud.githubusercontent.com/assets/6467815/18463193/0cf0aab4-793d-11e6-9128-5aaec3cde461.png)

mobile-4-measure-detailpage
![mobile-4-measure-detailpage](https://cloud.githubusercontent.com/assets/6467815/18463186/0c907216-793d-11e6-9421-610469a0934a.png)

mobile-5-candidate-detailpage
![mobile-5-candidate-detailpage](https://cloud.githubusercontent.com/assets/6467815/18463187/0cb926fc-793d-11e6-8c0d-905b5bac5483.png)

mobile-5-measure-supporters
![mobile-5-measure-supporters](https://cloud.githubusercontent.com/assets/6467815/18463190/0cc3ee02-793d-11e6-8830-514d1cd425a2.png)

![Uploading Mobile-6-Candidate-Contributions.png…]()

mobile-6-committee-detailpage
![mobile-6-committee-detailpage](https://cloud.githubusercontent.com/assets/6467815/18463189/0cc264b0-793d-11e6-8956-afc64f1c1f3d.png)

mobile-7-committee-contributors
![mobile-7-committee-contributors](https://cloud.githubusercontent.com/assets/6467815/18463192/0ce94a08-793d-11e6-8318-a51a2f7e3142.png)

**Comment by elinaru** [comment]
![mobile-6-candidate-contributions](https://cloud.githubusercontent.com/assets/6467815/18463732/1b9be732-7941-11e6-8eea-2d1c5f5de6ea.png)

**Comment by tdooner** [comment]
@elinaru Can you send these to me in a zip file (or something like that) and I will update the [mockups directory in disclosure-backend](https://github.com/caciviclab/disclosure-backend/tree/master/mockups)? Or if you are comfortable doing that yourself, go right ahead. We should have these somewhere more permanent than an open issue, is all I'm saying ;)

**Comment by elinaru** [comment]
These mocks are obsolete. Most recent mock-ups in prototypes here: 
ODCA-v19 Desktop: https://invis.io/978VSTHZS
ODCA-v19 Mobile: https://invis.io/RC8VSTKEM

**Comment by elinaru** [comment]
I can update the directory. In the meantime, the most up-to-date desktop
mock-ups are here: https://invis.io/TK8O67TEZ
