### ISSUE TITLE
Migrate to Jekyll

### ISSUE THREAD

**Issue by adborden** [caciviclab/caciviclab.github.io#4]
I think migrating to [jekyll](https://jekyllrb.com/) would make development the site a bit easier to folks. I've seen some people struggle to edit some of the json data files, and not understand why the changes don't work locally (IIRC, some pages won't even work properly). Jekyll would allow you to spin up a local webserver for development.

What do you think?

**Comment by bcipolli** [comment]
I'm a big fan of Jekyll. Collections, data, and auto-pagination are great tools for turning static data into formatted webpages. And of course the easy github integration is fantastic.

**Comment by jnmarcus** [comment]
Jekyll's great! I've built lots of stuff with it.  Let me know if you need a live reload/jekyll/sass gruntfile or anything.  I know I have one lying around here somewhere...
